<?php

namespace Anorgan\QueryLanguage;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-17 at 01:06:44.
 */
class ConditionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Condition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Condition('field', '=', 'value');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    
    /**
     * @covers Anorgan\QueryLanguage\Condition::__construct
     */
    public function testSettingValueViaContructorNormalizesIt()
    {
        $date = new \DateTime;
        $condition = new Condition('field', '=', 'value');
        $this->assertEquals('value', $condition->toArray()['value']);
    }
    
    /**
     * @covers Anorgan\QueryLanguage\Condition::normalizeValue
     */
    public function testNormalizeValueDoesNothingIfValueIsNotString()
    {
        $date = new \DateTime;
        $this->assertEquals($date, $this->object->normalizeValue($date));
    }

    /**
     * @covers Anorgan\QueryLanguage\Condition::denormalizeValue
     * @todo   Implement testDenormalizeValue().
     */
    public function testDenormalizeValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Condition::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Condition::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
