<?php

namespace Anorgan\QueryLanguage;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-19 at 23:39:09.
 */
class CompositeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Composite
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Composite(Composite::TYPE_AND);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    /**
     * @covers Anorgan\QueryLanguage\Composite::__construct
     * @covers Anorgan\QueryLanguage\Composite::getType
     * @covers Anorgan\QueryLanguage\Composite::count
     * @covers Anorgan\QueryLanguage\Composite::add
     */
    public function testSettingParamsViaConstructor()
    {
        $this->object->add(new Condition('field', '=', 'value'));
        $composite = new Composite(Composite::TYPE_OR, $this->object, $this->object);
        $this->assertEquals('OR', $composite->getType());
        $this->assertTrue($composite->hasParent());
        $this->assertEquals(1, $composite->count());
        $composite->add(new Condition('field', '=', 'value'));
        $this->assertEquals(2, $composite->count());
        
        $composite = new Composite(Composite::TYPE_OR, [$this->object], $this->object);
        $this->assertEquals(1, $composite->count());
    }
    
    /**
     * @covers Anorgan\QueryLanguage\Composite::back
     */
    public function testBack()
    {
        $this->assertSame($this->object, $this->object->back());
        $this->assertSame($this->object, $this->object->back()->back()->back());

        $composite = new Composite(Composite::TYPE_OR, [], $this->object);
        $this->assertSame($this->object, $this->object->back());
        
        $secondComposite = new Composite(Composite::TYPE_AND, [], $composite);
        $this->assertSame($composite, $secondComposite->back());
        $this->assertSame($this->object, $secondComposite->back()->back());
    }
    
    /**
     * @covers Anorgan\QueryLanguage\Composite::hasParent
     */
    public function testHasParent()
    {
        $this->assertFalse($this->object->hasParent());
        $composite = new Composite(Composite::TYPE_OR, [], $this->object);
        $this->assertTrue($composite->hasParent());
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::end
     */
    public function testEnd()
    {
        $this->assertSame($this->object, $this->object->end());
        
        $composite = new Composite(Composite::TYPE_OR, [], $this->object);
        $secondComposite = new Composite(Composite::TYPE_AND, [], $composite);
        $this->assertSame($this->object, $secondComposite->end());
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::addParts
     */
    public function testAddParts()
    {
        $this->assertEquals(0, $this->object->count());
        $this->object->addParts([
            new Composite(Composite::TYPE_AND, [new Condition('field', '=', 'value')]),
        ]);
        $this->assertEquals(1, $this->object->count());
        $this->object->addParts([
            new Composite(Composite::TYPE_OR, [new Condition('field', '=', 'value')]),
            new Condition('field', '=', 'value')
        ]);
        $this->assertEquals(3, $this->object->count());
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::add
     */
    public function testAdd()
    {
        $this->assertEquals(0, $this->object->count());

        $this->object->add(new Composite(Composite::TYPE_OR, [new Condition('field', '=', 'value')]));
        $this->object->add(new Condition('field', '=', 'value'));

        $this->assertEquals(2, $this->object->count());
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::add
     * @expectedException \InvalidArgumentException
     */
    public function testThrowsExceptionIfWrongArgumentPassedToAdd()
    {
        $this->object->add('a');
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::add
     */
    public function testAddingEmptyCompositionDoesNothing()
    {
        $this->assertEquals(0, $this->object->count());

        $this->object->add(new Composite('OR'));
        $this->assertEquals(0, $this->object->count());

        $this->object->add(new Condition('field', '=', 'value'));
        $this->assertEquals(1, $this->object->count());

    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::andX
     */
    public function testAndX()
    {
        $composite = new Composite(Composite::TYPE_OR, new Condition('field', '=', 'value'));
        $this->object->andX($composite);
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::orX
     * @todo   Implement testOrX().
     */
    public function testOrX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::count
     * @todo   Implement testCount().
     */
    public function testCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anorgan\QueryLanguage\Composite::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
